---

- name: install epel-release
  yum:
    name: epel-release
    state: latest
  delay: 10
  retries: 3
  register: result
  until: result is succeeded
  when: ansible_distribution == 'CentOS'

- name: install awx_packages
  package:
    name: '{{ awx_packages }}'
  delay: 10
  retries: 3
  register: result
  until: result is succeeded

- name: enable and start awx_services
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items: '{{ awx_services }}'

- name: install awx_pip_modules
  pip:
    name: '{{ awx_pip_modules }}'
    executable: pip3
